<<<<<<< HEAD
module.exports ={
	header:[
		'Capacity',
		'WTCount',
		'InverterCount',
		'WindSpeed_DevAverValue',
		'PVTSI_Aver',
		'TActPower',
		'ONL',
		'FaultCount',
		'OfflineCount',
		'RepairCount',
		'WFStandbyCount',
	],
	header1:[
		'Capacity',
		'WTCount',
		'InverterCount',
		'WindSpeed_DevAverValue',
		'PVTSI_Aver',
		'TActPower',
		'PVONL',
		'PVFLT',
		'PVOFL',
	]
=======
module.exports ={
	header:[
		'Capacity',
		'WTCount',
		'WindSpeed_DevAverValue',
		'TActPower',
		'RunCount_SOAM',
		'OfflineCount',
		'RepairCount',
		'FaultCount',
		'WFStandbyCount',
		'WFLIMCount',
	],
	header1:[
		'Capacity',
		'InverterCount',
		'PVTSI_Aver',
		'TActPower',
		'PVONL',
		'PVOFL',
		'PVFLT',
	]
>>>>>>> 9f1a2c4903f5ad6c45ec995e413fedb506a23e43
}