module.exports ={
	header:[
		'Capacity',
		'WTCount',
		'WindSpeed_DevAverValue',
		'TActPower',
		'ONL',
		'OfflineCount',
		'RepairCount',
		'FaultCount',
		'WFStandbyCount',
		'WFLIMCount',
	],
	header1:[
		'Capacity',
		'InverterCount',
		'PVTSI_Aver',
		'TActPower',
		'PVONL',
		'PVOFL',
		'PVFLT',
	]
}