module.exports ={
    "ModelData": {
        "650107": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "17",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "30585.3832",
            "PVTSI_Aver": "6306.3078",
            "Capacity": "49500",
            "TActPower": "3527.110",
            "DayEgyAt": "7043",
            "MonthEgyAt": "44799",
            "YearEgyAt": "7690",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "17",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "43893",
            "YearPlanTotEgyAt": "3148817",
            "WfStateCode": "Offline",
            "StatusCode": "LimitPow"
        },
        "650123": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "33",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "54067.4073",
            "PVTSI_Aver": "41778.5995",
            "Capacity": "49500",
            "TActPower": "89548.730",
            "DayEgyAt": "2878",
            "MonthEgyAt": "44429",
            "YearEgyAt": "66552",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "33",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "23386",
            "YearPlanTotEgyAt": "4325924",
            "WfStateCode": "Disconnect",
            "StatusCode": "DisComForPre"
        },
        "650124": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "33",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "63883.4728",
            "PVTSI_Aver": "32843.4305",
            "Capacity": "49500",
            "TActPower": "5467.770",
            "DayEgyAt": "8090",
            "MonthEgyAt": "46419",
            "YearEgyAt": "28130",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "33",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "45058",
            "YearPlanTotEgyAt": "691142",
            "WfStateCode": "LimitPower",
            "StatusCode": "Online"
        },
        "652111": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "126",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "494.4644",
            "PVTSI_Aver": "20773.1339",
            "Capacity": "99000",
            "TActPower": "98419.070",
            "DayEgyAt": "2618",
            "MonthEgyAt": "2483",
            "YearEgyAt": "29403",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "126",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "39533",
            "YearPlanTotEgyAt": "3462680",
            "WfStateCode": "Run",
            "StatusCode": "DisComForPre"
        },
        "652112": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "99",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "64527.4966",
            "PVTSI_Aver": "19689.5241",
            "Capacity": "99000",
            "TActPower": "83120.620",
            "DayEgyAt": "487",
            "MonthEgyAt": "48539",
            "YearEgyAt": "23188",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "99",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "23115",
            "YearPlanTotEgyAt": "4449909",
            "WfStateCode": "Disconnect",
            "StatusCode": "ProtoectStop"
        },
        "652113": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "33",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "37898.9328",
            "PVTSI_Aver": "60635.4895",
            "Capacity": "49500",
            "TActPower": "18853.020",
            "DayEgyAt": "6439",
            "MonthEgyAt": "12577",
            "YearEgyAt": "95423",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "33",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "49673",
            "YearPlanTotEgyAt": "3539466",
            "WfStateCode": "Disconnect",
            "StatusCode": "Unknown"
        },
        "652303": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "0",
            "InverterCount": "40",
            "WindSpeed_DevAverValue": "46490.1602",
            "PVTSI_Aver": "69032.0235",
            "Capacity": "2000",
            "TActPower": "29802.410",
            "DayEgyAt": "5803",
            "MonthEgyAt": "71109",
            "YearEgyAt": "95285",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "0",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "40",
            "CurMonthPlanEgyAt": "35382",
            "YearPlanTotEgyAt": "4556185",
            "WfStateCode": "Offline",
            "StatusCode": "Unknown"
        },
        "652304": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "0",
            "InverterCount": "40",
            "WindSpeed_DevAverValue": "52309.6964",
            "PVTSI_Aver": "61161.0954",
            "Capacity": "20000",
            "TActPower": "68249.310",
            "DayEgyAt": "4960",
            "MonthEgyAt": "89042",
            "YearEgyAt": "96160",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "0",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "40",
            "CurMonthPlanEgyAt": "21558",
            "YearPlanTotEgyAt": "3576548",
            "WfStateCode": "LimitPower",
            "StatusCode": "LimitPow"
        },
        "652305": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "0",
            "InverterCount": "40",
            "WindSpeed_DevAverValue": "30718.1934",
            "PVTSI_Aver": "64801.5961",
            "Capacity": "20000",
            "TActPower": "50713.170",
            "DayEgyAt": "451",
            "MonthEgyAt": "29994",
            "YearEgyAt": "99582",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "0",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "40",
            "CurMonthPlanEgyAt": "31211",
            "YearPlanTotEgyAt": "3260594",
            "WfStateCode": "Offline",
            "StatusCode": "Fault"
        },
        "652325": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "33",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "33489.8844",
            "PVTSI_Aver": "13106.8964",
            "Capacity": "49500",
            "TActPower": "22545.340",
            "DayEgyAt": "5398",
            "MonthEgyAt": "74486",
            "YearEgyAt": "15250",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "33",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "3161",
            "YearPlanTotEgyAt": "1134827",
            "WfStateCode": "Disconnect",
            "StatusCode": "LimitPow"
        },
        "654328": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "33",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "47831.4469",
            "PVTSI_Aver": "17875.5121",
            "Capacity": "49500",
            "TActPower": "81643.430",
            "DayEgyAt": "8894",
            "MonthEgyAt": "7477",
            "YearEgyAt": "89459",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "33",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "41134",
            "YearPlanTotEgyAt": "2679810",
            "WfStateCode": "LimitPower",
            "StatusCode": "Offline"
        },
        "654330": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "33",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "20620.3519",
            "PVTSI_Aver": "54025.2491",
            "Capacity": "49500",
            "TActPower": "64472.070",
            "DayEgyAt": "2735",
            "MonthEgyAt": "83117",
            "YearEgyAt": "35262",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "33",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "47463",
            "YearPlanTotEgyAt": "2175223",
            "WfStateCode": "Offline",
            "StatusCode": "DisComForPlc"
        },
        "836610": {
            "WFCount": "1",
            "PVCount": "1",
            "WTCount": "58",
            "InverterCount": "0",
            "WindSpeed_DevAverValue": "2642.4427",
            "PVTSI_Aver": "15197.0732",
            "Capacity": "99000",
            "TActPower": "4377.580",
            "DayEgyAt": "9549",
            "MonthEgyAt": "24787",
            "YearEgyAt": "36907",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "58",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "0",
            "CurMonthPlanEgyAt": "21202",
            "YearPlanTotEgyAt": "3675816",
            "WfStateCode": "Offline",
            "StatusCode": "Offline"
        },
        "8888800": {
            "WFCount": "13",
            "PVCount": "13",
            "WTCount": "498",
            "InverterCount": "120",
            "WindSpeed_DevAverValue": "64916.4776",
            "PVTSI_Aver": "38729.5029",
            "Capacity": "685500",
            "TActPower": "17066.400",
            "DayEgyAt": "5324",
            "MonthEgyAt": "64878",
            "YearEgyAt": "81322",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "498",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "120",
            "CurMonthPlanEgyAt": "3482",
            "YearPlanTotEgyAt": "2756035",
            "WfStateCode": "Offline",
            "StatusCode": "Online",
            "CurDayPowerCurve": {
                "Time": [
                    "00:00",
                    "00:15",
                    "00:30",
                    "00:45",
                    "01:00",
                    "01:15",
                    "01:30",
                    "01:45",
                    "02:00",
                    "02:15",
                    "02:30",
                    "02:45",
                    "03:00",
                    "03:15",
                    "03:30",
                    "03:45",
                    "04:00",
                    "04:15",
                    "04:30",
                    "04:45",
                    "05:00",
                    "05:15",
                    "05:30",
                    "05:45",
                    "06:00",
                    "06:15",
                    "06:30",
                    "06:45",
                    "07:00",
                    "07:15",
                    "07:30",
                    "07:45",
                    "08:00",
                    "08:15",
                    "08:30",
                    "08:45",
                    "09:00",
                    "09:15",
                    "09:30"
                ],
                "Value": [
                    6497,
                    5933,
                    5987,
                    2116,
                    1339,
                    2584,
                    2122,
                    2860,
                    4689,
                    971,
                    1622,
                    1568,
                    637,
                    7179,
                    6955,
                    3858,
                    6185,
                    4033,
                    3828,
                    7795,
                    3024,
                    5799,
                    1308,
                    6571,
                    4073,
                    6532,
                    2854,
                    2167,
                    546,
                    586,
                    4112,
                    1335,
                    4774,
                    7366,
                    1548,
                    1020,
                    3525,
                    7558
                ]
            },
            "WfsStateCode": "Disconnect"
        },
        "8888801": {
            "CurDayWindSpeedCurve": {
                "Time": [
                    "00:00",
                    "00:15",
                    "00:30",
                    "00:45",
                    "01:00",
                    "01:15",
                    "01:30",
                    "01:45",
                    "02:00",
                    "02:15",
                    "02:30",
                    "02:45",
                    "03:00",
                    "03:15",
                    "03:30",
                    "03:45",
                    "04:00",
                    "04:15",
                    "04:30",
                    "04:45",
                    "05:00",
                    "05:15",
                    "05:30",
                    "05:45",
                    "06:00",
                    "06:15",
                    "06:30",
                    "06:45",
                    "07:00",
                    "07:15",
                    "07:30",
                    "07:45",
                    "08:00",
                    "08:15",
                    "08:30",
                    "08:45",
                    "09:00",
                    "09:15",
                    "09:30"
                ],
                "Value": [
                    6,
                    6,
                    13,
                    5,
                    6,
                    12,
                    5,
                    2,
                    3,
                    1,
                    2,
                    1,
                    9,
                    14,
                    9,
                    14,
                    6,
                    13,
                    0,
                    4,
                    1,
                    7,
                    4,
                    4,
                    2,
                    2,
                    3,
                    7,
                    8,
                    11,
                    6,
                    0,
                    6,
                    3,
                    13,
                    0,
                    5,
                    14
                ]
            },
            "WFCount": "10",
            "WTCount": "498",
            "WindSpeed_DevAverValue": "20583.3196",
            "Capacity": "643500",
            "TActPower": "10467.760",
            "DayEgyAt": "4113",
            "MonthEgyAt": "12114",
            "YearEgyAt": "43501",
            "RunCount_SOAM": "0",
            "FaultCount": "0",
            "RepairCount": "0",
            "OfflineCount": "498",
            "WFStandbyCount": "0",
            "WFLIMCount": "0",
            "CurMonthPlanEgyAt": "11041",
            "YearPlanTotEgyAt": "595766",
            "WfsStateCode": "Disconnect"
        },
        "8888802": {
            "CurDayPVTSICurve": {
                "Time": [
                    "00:00",
                    "00:15",
                    "00:30",
                    "00:45",
                    "01:00",
                    "01:15",
                    "01:30",
                    "01:45",
                    "02:00",
                    "02:15",
                    "02:30",
                    "02:45",
                    "03:00",
                    "03:15",
                    "03:30",
                    "03:45",
                    "04:00",
                    "04:15",
                    "04:30",
                    "04:45",
                    "05:00",
                    "05:15",
                    "05:30",
                    "05:45",
                    "06:00",
                    "06:15",
                    "06:30",
                    "06:45",
                    "07:00",
                    "07:15",
                    "07:30",
                    "07:45",
                    "08:00",
                    "08:15",
                    "08:30",
                    "08:45",
                    "09:00",
                    "09:15",
                    "09:30"
                ],
                "Value": [
                    942,
                    1450,
                    449,
                    1705,
                    1237,
                    77,
                    1035,
                    1526,
                    467,
                    2,
                    364,
                    1883,
                    151,
                    946,
                    1545,
                    762,
                    1912,
                    1107,
                    1746,
                    1723,
                    854,
                    1122,
                    877,
                    367,
                    640,
                    1119,
                    1976,
                    1566,
                    1083,
                    773,
                    76,
                    986,
                    555,
                    356,
                    121,
                    155,
                    1461,
                    303
                ]
            },
            "PVCount": "3",
            "InverterCount": "120",
            "PVTSI_Aver": "61253.8831",
            "Capacity": "42000",
            "TActPower": "74074.240",
            "DayEgyAt": "1651",
            "MonthEgyAt": "294",
            "YearEgyAt": "15732",
            "PVONL": "0",
            "PVFLT": "0",
            "PVOFL": "120",
            "CurMonthPlanEgyAt": "38410",
            "YearPlanTotEgyAt": "2293529",
            "WfsStateCode": "Disconnect"
        },
        "guid": ""
    }
}